FROM amazonlinux:2023

RUN yum update -y && \
    yum install -y java-21-amazon-corretto unzip shadow-utils procps && \
    yum clean all

RUN useradd -m sonar

WORKDIR /opt

# Download SonarQube using ADD
ADD https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-26.1.0.118079.zip /opt/

RUN unzip sonarqube-26.1.0.118079.zip && \
    mv sonarqube-26.1.0.118079 sonarqube && \
    rm -f sonarqube-26.1.0.118079.zip

RUN chown -R sonar:sonar /opt/sonarqube

USER sonar

EXPOSE 9000

ENTRYPOINT ["/opt/sonarqube/bin/linux-x86-64/sonar.sh","console"]
